// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace DBControl
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"column1")]
            public string Column1 { get; set; }

            [ColumnName(@"Gender")]
            public string Gender { get; set; }

            [ColumnName(@"DOB")]
            public string DOB { get; set; }

            [ColumnName(@"Maths")]
            public float Maths { get; set; }

            [ColumnName(@"Physics")]
            public float Physics { get; set; }

            [ColumnName(@"Chemistry")]
            public float Chemistry { get; set; }

            [ColumnName(@"English")]
            public float English { get; set; }

            [ColumnName(@"Biology")]
            public float Biology { get; set; }

            [ColumnName(@"Economics")]
            public float Economics { get; set; }

            [ColumnName(@"History")]
            public float History { get; set; }

            [ColumnName(@"Civics")]
            public float Civics { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = "C:/Users/romam/Desktop/coursework/Project/DBControl/DBControl/MLModel1.zip";

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
