﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace DBControl
{
    public partial class MLModel1
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Maths", @"Maths"),new InputOutputColumnPair(@"Physics", @"Physics"),new InputOutputColumnPair(@"Chemistry", @"Chemistry"),new InputOutputColumnPair(@"English", @"English"),new InputOutputColumnPair(@"Biology", @"Biology"),new InputOutputColumnPair(@"Economics", @"Economics"),new InputOutputColumnPair(@"Civics", @"Civics")})      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"column1", @"column1"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"Gender", @"Gender"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"DOB", @"DOB"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Maths",@"Physics",@"Chemistry",@"English",@"Biology",@"Economics",@"Civics",@"column1",@"Gender",@"DOB"}))      
                                    .Append(mlContext.Regression.Trainers.FastForest(new FastForestRegressionTrainer.Options(){NumberOfTrees=4,FeatureFraction=1F,LabelColumnName=@"History",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
